2024-08-27T00:00:01 {"cpu": 0.56201171875, "cpu_total": 18, "cpu_usage": 0.031222873263888888, "memory": 17542.0, "memory_total": 31060.0, "memory_usage": 0.5647778493238892, "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "level": "INFO", "message": "Pipeline gcs_to_bq for run 29 in schedule 1 is alive.", "timestamp": 1724716801.080782, "uuid": "91d7156afddb444f8f6246bb5dbce56d"}
2024-08-27T00:00:01 {"cpu": 0.56201171875, "cpu_total": 18, "cpu_usage": 0.031222873263888888, "memory": 17558.0, "memory_total": 31060.0, "memory_usage": 0.5652929813264649, "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "level": "INFO", "message": "Pipeline gcs_to_bq for run 29 in schedule 1 is alive.", "timestamp": 1724716801.168323, "uuid": "d44d29eb5acc4fc08abea874662ddd52"}
2024-08-27T00:00:01 {"block_run_id": 85, "block_uuid": "load_taxi_gcs", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "level": "INFO", "message": "Execute PipelineRun 29, BlockRun 85: pipeline gcs_to_bq block load_taxi_gcs", "timestamp": 1724716801.25669, "uuid": "7fc4c059fcd74a5db95c61244175207b"}
2024-08-27T00:00:10 {"cpu": 0.572265625, "cpu_total": 18, "cpu_usage": 0.031792534722222224, "memory": 17647.0, "memory_total": 31060.0, "memory_usage": 0.568158403090792, "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "level": "INFO", "message": "Pipeline gcs_to_bq for run 29 in schedule 1 is alive.", "timestamp": 1724716810.21367, "uuid": "bdfae86daadf4e93908f4f1a4b4f58db"}
2024-08-27T00:00:15 {"block_run_id": 85, "block_uuid": "load_taxi_gcs", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "level": "INFO", "message": "BlockRun 85 (block_uuid: load_taxi_gcs) completes.", "timestamp": 1724716815.776557, "uuid": "ee041b232e0e483a90b0f7ae57bf5e6c"}
2024-08-27T00:00:20 {"cpu": 0.5712890625, "cpu_total": 18, "cpu_usage": 0.03173828125, "memory": 17587.0, "memory_total": 31060.0, "memory_usage": 0.5662266580811333, "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "level": "INFO", "message": "Pipeline gcs_to_bq for run 29 in schedule 1 is alive.", "timestamp": 1724716820.266609, "uuid": "627be0edef3140c7b2f1d6c441a61f8f"}
2024-08-27T00:00:30 {"cpu": 0.59765625, "cpu_total": 18, "cpu_usage": 0.033203125, "memory": 17805.0, "memory_total": 31060.0, "memory_usage": 0.5732453316162267, "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "level": "INFO", "message": "Pipeline gcs_to_bq for run 29 in schedule 1 is alive.", "timestamp": 1724716830.33404, "uuid": "74d4fda705944ed78850da331c5f2604"}
2024-08-27T00:00:30 {"block_run_id": 86, "block_uuid": "transform_staged_data", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "level": "INFO", "message": "Execute PipelineRun 29, BlockRun 86: pipeline gcs_to_bq block transform_staged_data", "timestamp": 1724716830.426491, "uuid": "b4fcd94a0b3c45e48182bda9aa169adc"}
2024-08-27T00:00:32 {"block_run_id": 86, "block_uuid": "transform_staged_data", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "level": "INFO", "message": "BlockRun 86 (block_uuid: transform_staged_data) completes.", "timestamp": 1724716832.928338, "uuid": "5a2ba654c6fa4073bec0778ceefe0fe3"}
2024-08-27T00:00:40 {"cpu": 0.6181640625, "cpu_total": 18, "cpu_usage": 0.034342447916666664, "memory": 17966.0, "memory_total": 31060.0, "memory_usage": 0.5784288473921443, "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "level": "INFO", "message": "Pipeline gcs_to_bq for run 29 in schedule 1 is alive.", "timestamp": 1724716840.417019, "uuid": "72e95a800397478897d17baadb1cb1cc"}
2024-08-27T00:00:40 {"block_run_id": 87, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "level": "INFO", "message": "Execute PipelineRun 29, BlockRun 87: pipeline gcs_to_bq block write_taxi_to_bq", "timestamp": 1724716840.497791, "uuid": "f026bab397ed4ff49fd166ff10d5d303"}
2024-08-27T00:00:50 {"cpu": 0.62841796875, "cpu_total": 18, "cpu_usage": 0.034912109375, "memory": 19208.0, "memory_total": 31060.0, "memory_usage": 0.6184159690920799, "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "level": "INFO", "message": "Pipeline gcs_to_bq for run 29 in schedule 1 is alive.", "timestamp": 1724716850.486737, "uuid": "97702916862c43a1aa3509fe0c43bda4"}
2024-08-27T00:01:00 {"cpu": 0.6865234375, "cpu_total": 18, "cpu_usage": 0.038140190972222224, "memory": 19130.0, "memory_total": 31060.0, "memory_usage": 0.6159047005795235, "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "level": "INFO", "message": "Pipeline gcs_to_bq for run 29 in schedule 1 is alive.", "timestamp": 1724716860.540132, "uuid": "6580b735194047ada0a4a770e624da73"}
2024-08-27T00:01:10 {"cpu": 0.701171875, "cpu_total": 18, "cpu_usage": 0.03895399305555555, "memory": 18859.0, "memory_total": 31060.0, "memory_usage": 0.6071796522858982, "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "level": "INFO", "message": "Pipeline gcs_to_bq for run 29 in schedule 1 is alive.", "timestamp": 1724716870.573337, "uuid": "9183d851ccd34d4fafbdbdf6cc926c66"}
2024-08-27T00:01:20 {"cpu": 0.70458984375, "cpu_total": 18, "cpu_usage": 0.039143880208333336, "memory": 18950.0, "memory_total": 31060.0, "memory_usage": 0.6101094655505473, "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "level": "INFO", "message": "Pipeline gcs_to_bq for run 29 in schedule 1 is alive.", "timestamp": 1724716880.616275, "uuid": "d1a060117d0844f19cdaa3e5a175a050"}
2024-08-27T00:01:30 {"cpu": 0.70849609375, "cpu_total": 18, "cpu_usage": 0.039360894097222224, "memory": 19037.0, "memory_total": 31060.0, "memory_usage": 0.6129104958145525, "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "level": "INFO", "message": "Pipeline gcs_to_bq for run 29 in schedule 1 is alive.", "timestamp": 1724716890.656645, "uuid": "20466806b2024f6a806a38ffdd8bdbcd"}
2024-08-27T00:01:35 {"block_run_id": 87, "block_uuid": "write_taxi_to_bq", "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "level": "EXCEPTION", "message": "BlockRun 87 (block_uuid: write_taxi_to_bq) failed.", "timestamp": 1724716895.055752, "uuid": "7ff0fda585264bf4ad7ce07774b43b59", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1154, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1673, in execute_sync\n    return __execute()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1650, in __execute\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1552, in __execute\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1892, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/sql/__init__.py\", line 746, in _execute_block\n    return execute_sql_code(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/sql/__init__.py\", line 212, in execute_sql_code\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/sql/__init__.py\", line 204, in execute_sql_code\n    result = loader.load(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py\", line 194, in load\n    ).to_dataframe()\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py\", line 1890, in to_dataframe\n    query_result = wait_for_query(self, progress_bar_type, max_results=max_results)\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/_tqdm_helpers.py\", line 104, in wait_for_query\n    return query_job.result(max_results=max_results)\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py\", line 1595, in result\n    do_get_result()\n  File \"/usr/local/lib/python3.10/site-packages/google/api_core/retry.py\", line 372, in retry_wrapped_func\n    return retry_target(\n  File \"/usr/local/lib/python3.10/site-packages/google/api_core/retry.py\", line 207, in retry_target\n    result = target()\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py\", line 1584, in do_get_result\n    super(QueryJob, self).result(retry=retry, timeout=timeout)\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/base.py\", line 952, in result\n    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/google/api_core/future/polling.py\", line 261, in result\n    raise self._exception\ngoogle.api_core.exceptions.NotFound: 404 Not found: Table gold-bruin-429014-v5:trips_data_all.taxi_yellow was not found in location US\n\nLocation: US\nJob ID: 8ca43391-8792-487a-9da1-bb77f72b04ea\n\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 787, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 106, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 58, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1735, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 334, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 641, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 20, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 121, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 198, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 351, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 315, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1232, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 682, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 465, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["404 Not found: Table gold-bruin-429014-v5:trips_data_all.taxi_yellow was not found in location US\n\nLocation: US\nJob ID: 8ca43391-8792-487a-9da1-bb77f72b04ea\n"]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 647, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 621, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1154, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1673, in execute_sync
    return __execute()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1650, in __execute
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1552, in __execute
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1892, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/sql/__init__.py", line 746, in _execute_block
    return execute_sql_code(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/sql/__init__.py", line 212, in execute_sql_code
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/sql/__init__.py", line 204, in execute_sql_code
    result = loader.load(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py", line 194, in load
    ).to_dataframe()
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py", line 1890, in to_dataframe
    query_result = wait_for_query(self, progress_bar_type, max_results=max_results)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/_tqdm_helpers.py", line 104, in wait_for_query
    return query_job.result(max_results=max_results)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py", line 1595, in result
    do_get_result()
  File "/usr/local/lib/python3.10/site-packages/google/api_core/retry.py", line 372, in retry_wrapped_func
    return retry_target(
  File "/usr/local/lib/python3.10/site-packages/google/api_core/retry.py", line 207, in retry_target
    result = target()
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py", line 1584, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/base.py", line 952, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: Table gold-bruin-429014-v5:trips_data_all.taxi_yellow was not found in location US

Location: US
Job ID: 8ca43391-8792-487a-9da1-bb77f72b04ea

2024-08-27T00:01:40 {"cpu": 0.72314453125, "cpu_total": 18, "cpu_usage": 0.04017469618055555, "memory": 18053.0, "memory_total": 31060.0, "memory_usage": 0.5812298776561494, "pipeline_run_id": 29, "pipeline_schedule_id": 1, "pipeline_uuid": "gcs_to_bq", "hostname": "34783f7a41ac", "level": "INFO", "message": "Pipeline gcs_to_bq for run 29 in schedule 1 is alive.", "timestamp": 1724716900.704978, "uuid": "4f67d9366221416b9c1ac78bc3997ab2"}
